# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Marcus Semblano
author-title: DevOps Engineer
gravatar: 6ee5fa9ebc36f5390b1e4dd1712cbe2f
email: msemblano@gmail.com
twitter: semblano
github: semblano
googleplus: 
facebook: 
linkedin: marcussemblano
bio: "System Analyst with over 7 years of experience on software development, Linux Distro customization, team leadership and infrastructure automation.

  I've been working with open source technologies, coding shell script, python and ruby.
  Recently, I've been working with new technologies like Vagrant, Docker, RabbitMQ, and learning new languages, like ruby and Go. Improving infrastructure automation with CHEF, to deploy/maintain a large number of machines on Amazon Web Service (AWS). Building CI/CD with Jenkins and monitoring with Sensu.

  Experience with RedHat Enterprise Linux, CentOS, OpenSuse, Debian, Ubuntu, OpenClient (IBM internal Linux distribution) and Metasys (custom educational Linux distribution).
  Academic experience with Data Warehouse and Data modeling.

  Additional experience with computer hardware design in Verilog and VHDL, based on my Electrical Engineering academic background."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
# 1 - Studying
# 2 - Personal lab
# 3 - Some professional experience
# 4 - Currently working with
# 5 - Major experience with
# If you don't want one of the sections below, leave the variable without any values

back-end:
  - name: Ruby
    level: 4
  - name: Python
    level: 4
  - name: GoLang
    level: 2
  - name: C
    level: 1

db:
  - name: MySQL
    level: 4
  - name: PostgreSQL
    level: 3
  - name: InfluxDB
    level: 3
  - name: CayleyDB
    level: 2
  - name: Oracle
    level: 1

devops:
  - name: Chef.io
    level: 5
  - name: Docker
    level: 3
  - name: Vagrant
    level: 3
  - name: Jenkins
    level: 3
  - name: Git
    level: 5
  - name: Continuous Integration
    level: 3
  - name: Continuous Delivery
    level: 2

methodologies:
  - name: Agile Methodologies
    level: 3
  - name: Scrum
    level: 4
  - name: RUP
    level: 3

others:
  - name: Web Services
    level: 5
  - name: REST
    level: 5
  - name: JEE, JSF, JPA, EJB, CDI
    level: 3
  - name: iReport, Jasper Reports
    level: 2
  - name: Hibernate
    level: 3
  - name: Grails
    level: 2
  - name: Symfony
    level: 3
  - name: Twig
    level: 4
  - name: Doctrine ORM
    level: 3
  - name: Laravel, Blade, Eloquent ORM
    level: 5
  - name: Ruby on Rails
    level: 3
  - name: MEAN Stack
    level: 4
  - name: Spring
    level: 3

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
